FROM oven/bun:1.1.29 AS base
WORKDIR /app

ARG STRIPE_PUBLISHABLE_KEY
ARG STRIPE_ADD_ONS_PRICING_TABLE_ID
ARG STRIPE_SUBSCRIPTION_PRICING_TABLE_ID
ARG FIREBASE_CLIENT_MAIL
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG PRODUCTION_CLOUD_FC_REGION
ARG ENV

ENV STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
ENV STRIPE_SUBSCRIPTION_PRICING_TABLE_ID=$STRIPE_SUBSCRIPTION_PRICING_TABLE_ID
ENV STRIPE_ADD_ONS_PRICING_TABLE_ID=$STRIPE_ADD_ONS_PRICING_TABLE_ID
ENV FIREBASE_CLIENT_MAIL=$FIREBASE_CLIENT_MAIL
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID
ENV PRODUCTION_CLOUD_FC_REGION=$PRODUCTION_CLOUD_FC_REGION
ENV ENV=$ENV

ENV HUSKY=0

COPY . .

RUN bun install --frozen-lockfile

RUN bun run build
